
project_id = "wxwbxupdisbofesaygqj"

[functions.validate-ghl-number]
verify_jwt = false

[functions.validate-integration]
verify_jwt = false

[functions.generate-with-openai]
verify_jwt = false

[functions.notify-team-leader]
verify_jwt = false

[functions.cybersource-payment]
verify_jwt = false

[functions.gcp-vision-analyze]
verify_jwt = false

[functions.web-enquiry-submit]
verify_jwt = false

[functions.organization-invite]
verify_jwt = true

[functions.hello-world]
verify_jwt = false

[functions.generate-demo-data]
verify_jwt = false

[functions.brevo-email-sender]
verify_jwt = false
