
# Configuration for Cloudflare Pages
[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-package-lock"
  BUN_ENABLED = "false"

[build.processing]
  skip_on_error = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Custom domain configuration
[routes]
  pattern = "tradeease.app/*"
  zone_name = "tradeease.app"
