version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: trade-ease-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=tradeease123
      - N8N_ENCRYPTION_KEY=your-secret-encryption-key-change-this
    volumes:
      - ./n8n-data:/home/node/.n8n
    networks:
      - trade-ease-network

networks:
  trade-ease-network:
    driver: bridge
