version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_CORS_ENABLED=true
      - N8N_CORS_ORIGIN=http://localhost:8080
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
