version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: trade-ease-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env.n8n
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./n8n-workflows:/workflows
    networks:
      - trade-ease-network

networks:
  trade-ease-network:
    driver: bridge
